source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ColorGaugeView_Example', :exclusive => true do
  pod "ColorGaugeView", :path => "../"
end

target 'ColorGaugeView_Tests', :exclusive => true do
  pod "ColorGaugeView", :path => "../"

  pod 'FBSnapshotTestCase'
end
